language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  # latest 4 versions plus the oldest supported version should be present
  - dmd-2.087.1
  - dmd-2.076.1
  - ldc-1.16.0
  - ldc-1.15.0
  - ldc-1.14.0
  - ldc-1.13.0
  - ldc-1.12.0
  - ldc-1.6.0
  - dmd-beta
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=kqueue
    - CONFIG=libasync

matrix:
  allow_failures:
    - d: dmd-beta
  exclude:
    - env: CONFIG=libasync
    - os: osx
      env: CONFIG=epoll
    - os: linux
      env: CONFIG=kqueue
    - os: osx
      d: dmd-beta

script: ./travis-ci.sh

sudo: false
