language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.073.0
  - dmd-2.070.2
  - ldc-1.1.0-beta6
  - ldc-1.0.0
  - dmd-beta
  - dmd-2.072.2
  - dmd-2.071.2

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=kqueue
    - CONFIG=libasync

matrix:
  allow_failures:
  exclude:
    - env: CONFIG=libasync
    - os: osx
      env: CONFIG=epoll
    - os: linux
      env: CONFIG=kqueue
    - os: osx
      d: dmd-2.071.2
    - os: osx
      d: dmd-2.070.2
    - os: osx
      d: ldc-1.1.0-beta6
    - os: osx
      d: ldc-1.0.0

script: ./travis-ci.sh

sudo: false
