language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.075.0
  - dmd-2.071.2
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.0
  - dmd-beta
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=kqueue
    - CONFIG=libasync

matrix:
  allow_failures:
    - d: dmd-beta
  exclude:
    - env: CONFIG=libasync
    - os: osx
      env: CONFIG=epoll
    - os: linux
      env: CONFIG=kqueue
    - os: osx
      d: dmd-2.074.1
    - os: osx
      d: dmd-2.073.2
    - os: osx
      d: dmd-2.072.2
    - os: osx
      d: dmd-2.071.2
    - os: osx
      d: dmd-beta
    - os: osx
      d: ldc-1.3.0
    - os: osx
      d: ldc-1.2.0
    - os: osx
      d: ldc-1.1.0

script: ./travis-ci.sh

sudo: false
